version: "3.9"
services:
  ros2:
    build: .
    network_mode: "host"
    volumes:
      - /home/fcheng/src/docker/ros:/home/ros
      - /home/fcheng/src/cubie-1:/ros2
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/i2c-1
    tty: true
    environment:
      - DISPLAY
